expanded-guideline-ods-5
openpreserve/sheets-preservation-spec pull request #37
Opened 2023-06-23 13:34 UTC by Asbjoedt

2023-06-27 10:35 UTC, carlwilson reviewed
I'm still uncomfortable about the talk of removal without any consideration of the technical process of removal. It's not as simple as deleting a file and feels like an encouragement to take preservation risks.

2023-06-27 10:35 UTC, carlwilson commented
Again, we're conflicted here @Asbjoedt

2023-06-27 11:14 UTC, Asbjoedt commented
If there's no appropriate automatic solutions for this, it may be a manual handling of the document by opening it in an application and replacing or removing the embedded files. This should not result in any technical malformities of the spreadsheet. Regarding the automatic solution, we cannot expect any automatic solution to be created by the market or any organisation unless the specification mandating this approach exists. First spec, then tools.

Discussing automatic removal of data from spreadsheets is something you have created an issue on, and we may keep the disucssion there IMO.

I resolved the conflict.

2023-06-28 15:16 UTC, RvanVeenendaal requested changes

2023-06-29 07:11 UTC, Asbjoedt commented on Draft v1.0/Specification.md
> +| ODS_5 | Embedded objects are allowed in the ODF standard, and you may encounter these. Typically, the embedded object is an image file and very often so a logo image, but embedded objects may also
Kaido and Asbjørn looked at your proposed text and we think it is excellent and have adopted it in the pull request.

2023-06-29 07:13 UTC, kivilaan approved these changes

2023-06-29 09:35 UTC, RvanVeenendaal approved these changes

2023-06-29 09:35 UTC, merged